### ISSUE TITLE
v2.2.2 to v1.2.2

### ISSUE THREAD

**Issue by NoxFly** [douzi8/file-system#16]
Hello,

`npm i file-system` -> installs the v2.2.2

Npm then tells us there are 3 high severities.

only way to fix that is to run `npm audit fix --force`.

It changes the fs version from 2.2.2 to 1.2.2. But then if you run it, you'll crash and get this error : 

```
<projectPath>node_modules\file-system\vendor\util.js:34
      target[key] = value;
                  ^

TypeError: Cannot set property 'isExternal' of undefined
    at extend (<projectPath>node_modules\file-system\vendor\util.js:34:19)
    at extend (<projectPath>node_modules\file-system\vendor\util.js:32:7)
    at Object.<anonymous> (<projectPath>node_modules\file-system\vendor\util.js:41:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (<projectPath>node_modules\file-system\index.js:6:12)
```

**Comment by convict-git** [comment]
facing the same issue
